# Barchyreborn Hyprland Main Config

# 1. Theme Variables (Must be first)
source = ~/.config/hypr/themes/current.conf

# 2. Defaults (Barchyreborn provides these)
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/configs/keybinds.conf
source = ~/.config/hypr/configs/autostart.conf

# 3. User Overrides
source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/windowrules.conf
source = ~/.config/hypr/configs/variables.conf
