# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    follow_mouse = 1

    touchpad {
        natural_scroll = true
    }
}

# gestures {
#     workspace_swipe = true
#     workspace_swipe_fingers = 3
# }

# https://wiki.hyprland.org/Configuring/Variables/#cursor
cursor {
    hide_on_key_press = true
}
