general {
  gaps_in = 5
  gaps_out = 10
  border_size = 2
  col.active_border = $accent
  col.inactive_border = $color8
  layout = dwindle
}

decoration {
  rounding = 8
  blur {
    enabled = true
    size = 5
    passes = 3
  }
}
